Repository scalar-labs/scalardl, pull requests merged in 2022-08, with the labels that each got.

#34 Update the Auditor getting started doc
  docs/getting-started-auditor.md
Labels: enhancement

#26 Update docs for 3.5.0 release
  README.md
  docs/getting-started-auditor.md
  docs/getting-started.md
  docs/how-to-use-proof.md
  docs/how-to-write-contract.md
  docs/how-to-write-function.md
  docs/implementation.md
  docs/index.md
Labels: improvement

#30 Update Scalar DL compatibility test matrix
  docs/compatibility.md
Labels: documentation

#36 Fix broken URL about database schema in function docs
  docs/how-to-write-function.md
Labels: documentation
