Repository scalar-labs/scalardl, pull requests merged in 2025-05, with the labels that each got.

#124 Add join functionality in select contract
  common/src/main/java/com/scalar/dl/genericcontracts/table/v1_0_0/Constants.java
  generic-contracts/src/main/java/com/scalar/dl/genericcontracts/table/v1_0_0/Select.java
  generic-contracts/src/test/java/com/scalar/dl/genericcontracts/table/v1_0_0/SelectTest.java
Labels: enhancement

#127 Revise scan and index data structure
  common/src/main/java/com/scalar/dl/genericcontracts/table/v1_0_0/Constants.java
  generic-contracts/src/main/java/com/scalar/dl/genericcontracts/table/v1_0_0/Insert.java
  generic-contracts/src/main/java/com/scalar/dl/genericcontracts/table/v1_0_0/Scan.java
  generic-contracts/src/test/java/com/scalar/dl/genericcontracts/table/v1_0_0/InsertTest.java
  generic-contracts/src/test/java/com/scalar/dl/genericcontracts/table/v1_0_0/ScanTest.java
Labels: improvement

#128 Revise README to include links to docs for better guidance
  README.md
Labels: documentation

#138 Fix numeric value handling and add integration tests for table-based generic contracts
  common/src/main/java/com/scalar/dl/genericcontracts/table/v1_0_0/Constants.java
  common/src/main/java/com/scalar/dl/ledger/server/BaseServer.java
  generic-contracts/conf/table-authenticity-management-contracts.toml
  generic-contracts/src/integration-test/java/com/scalar/dl/genericcontracts/GenericContractEndToEndTestBase.java
  generic-contracts/src/integration-test/java/com/scalar/dl/genericcontracts/GenericContractObjectAndCollectionEndToEndTest.java
  generic-contracts/src/integration-test/java/com/scalar/dl/genericcontracts/GenericContractTableEndToEndTest.java
  generic-contracts/src/main/java/com/scalar/dl/genericcontracts/table/v1_0_0/Create.java
  generic-contracts/src/main/java/com/scalar/dl/genericcontracts/table/v1_0_0/GetAssetId.java
  generic-contracts/src/main/java/com/scalar/dl/genericcontracts/table/v1_0_0/Insert.java
  generic-contracts/src/main/java/com/scalar/dl/genericcontracts/table/v1_0_0/Scan.java
  generic-contracts/src/test/java/com/scalar/dl/genericcontracts/table/v1_0_0/CreateTest.java
  generic-contracts/src/test/java/com/scalar/dl/genericcontracts/table/v1_0_0/GetAssetIdTest.java
  generic-contracts/src/test/java/com/scalar/dl/genericcontracts/table/v1_0_0/InsertTest.java
  generic-contracts/src/test/java/com/scalar/dl/genericcontracts/table/v1_0_0/ScanTest.java
Labels: improvement

#139 Add update feature for table-based generic contracts
  common/src/main/java/com/scalar/dl/genericcontracts/table/v1_0_0/Constants.java
  generic-contracts/conf/table-authenticity-management-contracts.toml
  generic-contracts/src/integration-test/java/com/scalar/dl/genericcontracts/GenericContractTableEndToEndTest.java
  generic-contracts/src/main/java/com/scalar/dl/genericcontracts/table/v1_0_0/Update.java
  generic-contracts/src/test/java/com/scalar/dl/genericcontracts/table/v1_0_0/UpdateTest.java
Labels: enhancement

#144 Fix JVM buffer sizes for Cosmos DB integeration tests
  .github/workflows/storage-compatibility-check.yaml
Labels: improvement

#142 Fix CVE-2025-22869
  ledger/Dockerfile
Labels: bugfix

#150 Simplify join logic by adding table reference in the Scan contract
  common/src/main/java/com/scalar/dl/genericcontracts/table/v1_0_0/Constants.java
  generic-contracts/src/main/java/com/scalar/dl/genericcontracts/table/v1_0_0/Scan.java
  generic-contracts/src/main/java/com/scalar/dl/genericcontracts/table/v1_0_0/Select.java
  generic-contracts/src/test/java/com/scalar/dl/genericcontracts/table/v1_0_0/SelectTest.java
Labels: improvement

#141 Add validate-ledger for assets created by table-based generic contracts
  client/src/main/java/com/scalar/dl/client/service/GenericContractClientService.java
  client/src/main/java/com/scalar/dl/client/tool/GenericContractLedgerValidation.java
  client/src/test/java/com/scalar/dl/client/service/GenericContractClientServiceTest.java
  client/src/test/java/com/scalar/dl/client/tool/GenericContractLedgerValidationTest.java
  common/src/main/java/com/scalar/dl/genericcontracts/AssetType.java
  generic-contracts/src/integration-test/java/com/scalar/dl/genericcontracts/GenericContractObjectAndCollectionEndToEndTest.java
  generic-contracts/src/integration-test/java/com/scalar/dl/genericcontracts/GenericContractTableEndToEndTest.java
Labels: enhancement
